<?php
// Variables
return [
    "creatorName" => "FlutterArc",
    "creatorUrl" => "https://flutterarc.com",
    "templateName" => env("APP_NAME"),
    "templateSuffix" => "App",
    "templateVersion" => "1.0.0",
    "templateFree" => false,
    "templateDescription" => "",
    "templateKeyword" => "",
    "licenseUrl" => "",
    "livePreview" => "",
    "productPage" => "",
    "support" => "",
    "moreThemes" => "",
    "documentation" => "",
    "generator" => "",
    "changelog" => "",
    "repository" => "",
    "gitAuthor" => "FlutterArc",
    "gitRepo" => "",
    "facebookUrl" => "",
    "twitterUrl" => "",
    "githubUrl" => "",
    "dribbbleUrl" => "",
    "instagramUrl" => "",
    "flKey" => env("FL_ACCESS"),
    "flUserId" => env("FL_USER_ID"),
    // Freelancer API base — point at https://www.freelancer-sandbox.com in dev.
    "flBase" => env("FL_BASE_URL", "https://www.freelancer.com"),
    // Dev-only: fabricate Freelancer chat data locally (no network in or out).
    "flFake" => env("FL_FAKE", false),
    "openAIKey" => env('OPENAI_API_KEY'),
    "gamificationIngestToken" => env('GAMIFICATION_INGEST_TOKEN'),
    "ingestToken" => env('INGEST_TOKEN', env('GAMIFICATION_INGEST_TOKEN')),
];
