<?php
// Variables
return [
    "creatorName" => "FlutterArc",
    "creatorUrl" => "https://flutterarc.com",
    "templateName" => env("APP_NAME"),
    "templateSuffix" => "App",
    "templateVersion" => "1.0.0",
    "templateFree" => false,
    "templateDescription" => "",
    "templateKeyword" => "",
    "licenseUrl" => "",
    "livePreview" => "",
    "productPage" => "",
    "support" => "",
    "moreThemes" => "",
    "documentation" => "",
    "generator" => "",
    "changelog" => "",
    "repository" => "",
    "gitAuthor" => "FlutterArc",
    "gitRepo" => "",
    "facebookUrl" => "",
    "twitterUrl" => "",
    "githubUrl" => "",
    "dribbbleUrl" => "",
    "instagramUrl" => "",
    "flKey" => env("FL_ACCESS"),
    "flUserId" => env("FL_USER_ID"),
    "openAIKey" => env('OPENAI_API_KEY'),
    'slackWebHook' => env('SLACK_WEBHOOK_URL'),
    'slackApiToken' => env('SLACK_API_TOKEN'),
    'slackAuthKey' => env('SLACK_OAUTH_TOKEN')
];
